package com.test.user.model;

// Generated 2013-12-30 14:28:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TdMMenus generated by hbm2java
 */
public class TdMMenus implements java.io.Serializable {

	private Long infoId;
	private String menuCode;
	private String menuName;
	private String menuUrl;
	private String menuDesc;
	
	public TdMMenus() {
	}

	public TdMMenus(String menuCode, String menuName) {
		this.menuCode = menuCode;
		this.menuName = menuName;
	}

	public TdMMenus(String menuCode, String menuName, String menuUrl,
			String menuDesc, Set<TdMRolemenu> tdMRolemenus) {
		this.menuCode = menuCode;
		this.menuName = menuName;
		this.menuUrl = menuUrl;
		this.menuDesc = menuDesc;
		
	}

	public Long getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Long infoId) {
		this.infoId = infoId;
	}

	public String getMenuCode() {
		return this.menuCode;
	}

	public void setMenuCode(String menuCode) {
		this.menuCode = menuCode;
	}

	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	public String getMenuUrl() {
		return this.menuUrl;
	}

	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl;
	}

	public String getMenuDesc() {
		return this.menuDesc;
	}

	public void setMenuDesc(String menuDesc) {
		this.menuDesc = menuDesc;
	}

	
}
