package com.test.user.model;

// Generated 2013-12-30 14:28:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TdMRoles generated by hbm2java
 */
public class TdMRoles implements java.io.Serializable {

	private Long infoId;
	private String roleCode;
	private String roleName;
	private String roleDesc;
	

	public TdMRoles() {
	}

	public TdMRoles(String roleCode, String roleName) {
		this.roleCode = roleCode;
		this.roleName = roleName;
	}

	public TdMRoles(String roleCode, String roleName, String roleDesc,
			 Set<TdMRolemenu> tdMRolemenus) {
		this.roleCode = roleCode;
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		
	}

	public Long getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Long infoId) {
		this.infoId = infoId;
	}

	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	

}
