package com.test.user.model;

// Generated 2013-12-30 14:28:10 by Hibernate Tools 3.4.0.CR1

/**
 * TdMRolemenu generated by hbm2java
 */
public class TdMRolemenu implements java.io.Serializable {

	private Long infoId;
	private TdMMenus tdMMenus;
	private TdMRoles tdMRoles;
	private Integer menuNum;
	private String paramValue;
	private Long parentId;
	private Integer depth;

	public TdMRolemenu() {
	}

	public TdMRolemenu(TdMMenus tdMMenus, TdMRoles tdMRoles) {
		this.tdMMenus = tdMMenus;
		this.tdMRoles = tdMRoles;
	}

	public TdMRolemenu(TdMMenus tdMMenus, TdMRoles tdMRoles, Integer menuNum,
			String paramValue, Long parentId, Integer depth) {
		this.tdMMenus = tdMMenus;
		this.tdMRoles = tdMRoles;
		this.menuNum = menuNum;
		this.paramValue = paramValue;
		this.parentId = parentId;
		this.depth = depth;
	}

	public Long getInfoId() {
		return this.infoId;
	}

	public void setInfoId(Long infoId) {
		this.infoId = infoId;
	}

	public TdMMenus getTdMMenus() {
		return this.tdMMenus;
	}

	public void setTdMMenus(TdMMenus tdMMenus) {
		this.tdMMenus = tdMMenus;
	}

	public TdMRoles getTdMRoles() {
		return this.tdMRoles;
	}

	public void setTdMRoles(TdMRoles tdMRoles) {
		this.tdMRoles = tdMRoles;
	}

	public Integer getMenuNum() {
		return this.menuNum;
	}

	public void setMenuNum(Integer menuNum) {
		this.menuNum = menuNum;
	}

	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public Integer getDepth() {
		return this.depth;
	}

	public void setDepth(Integer depth) {
		this.depth = depth;
	}

}
